<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0397954e-63d2-48b6-a581-a586951257cc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="NodaTime" Version="3.3.3" />
    <Content Update="Contracts/procesos_operativos.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
