// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tdv2.Infrastructure;

#nullable disable

namespace Tdv2.Migrations
{
    [DbContext(typeof(Tdv2DbContext))]
    partial class Tdv2DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tdv2.Domain.Entities.AccessContext", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("session_hash")
                        .IsFixedLength();

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("revision");

                    b.Property<string>("Selection")
                        .HasColumnType("text")
                        .HasColumnName("selection");

                    b.HasKey("Id")
                        .HasName("tdv2_access_contexts_pkey");

                    b.ToTable("tdv2_access_contexts", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entity");

                    b.Property<string>("Ip")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ip");

                    b.Property<string>("Meta")
                        .HasColumnType("json")
                        .HasColumnName("meta");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ur")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ur");

                    b.Property<string>("Ur2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ur2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("activity_logs_pkey");

                    b.ToTable("activity_logs", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.CatalogSynchronization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fuente");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completada_en");

                    b.Property<int>("Records")
                        .HasColumnType("integer")
                        .HasColumnName("registros");

                    b.HasKey("Id")
                        .HasName("sincronizacion_catalogos_pkey");

                    b.ToTable("sincronizacion_catalogos", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.FormBlock", b =>
                {
                    b.Property<string>("UnitId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id_ur");

                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("bloque");

                    b.Property<long>("ContextRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision_contexto");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vence_en");

                    b.Property<string>("Holder")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("titular");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id");

                    b.Property<string>("SessionHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sesion");

                    b.Property<Guid?>("TabId")
                        .HasColumnType("uuid")
                        .HasColumnName("pestana");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("UnitId", "Key");

                    b.HasIndex("UnitId", "ExpiresAt");

                    b.ToTable("formato_bloques", "public", t =>
                        {
                            t.HasCheckConstraint("formato_bloques_version_ck", "version >= 0");
                        });
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.FormMutation", b =>
                {
                    b.Property<string>("UnitId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id_ur");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("operacion");

                    b.Property<long>("ContextRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision_contexto");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("respuesta");

                    b.Property<string>("SessionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sesion");

                    b.Property<Guid>("TabId")
                        .HasColumnType("uuid")
                        .HasColumnName("pestana");

                    b.HasKey("UnitId", "Id");

                    b.ToTable("formato_operaciones", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.FormPosition", b =>
                {
                    b.Property<string>("UnitId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id_ur");

                    b.Property<string>("Actor")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("actor");

                    b.Property<string>("Effective")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("efectivo");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("seccion");

                    b.HasKey("UnitId", "Actor", "Effective");

                    b.ToTable("formato_posiciones", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.GraphToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Expires")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("expires");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("ms_graph_tokens_pkey");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ms_graph_tokens_user_id_key");

                    b.ToTable("ms_graph_tokens", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.IldaAreaInformation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("id_origen");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("datos");

                    b.Property<string>("Information")
                        .HasColumnType("text")
                        .HasColumnName("informacion_generada");

                    b.Property<bool>("Present")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("presente");

                    b.Property<DateTime>("SynchronizedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sincronizado_en");

                    b.Property<string>("Ur2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ur2");

                    b.HasKey("Id")
                        .HasName("ilda_informacion_area_pkey");

                    b.HasIndex("Present")
                        .HasDatabaseName("ilda_informacion_area_presente_index");

                    b.HasIndex("Ur2")
                        .HasDatabaseName("ilda_informacion_area_ur2_index");

                    b.ToTable("ilda_informacion_area", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.InstitutionalSynchronization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completada_en");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("resumen");

                    b.HasKey("Id")
                        .HasName("sincronizaciones_institucionales_pkey");

                    b.ToTable("sincronizaciones_institucionales", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.OAuthAttempt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("state_hash")
                        .IsFixedLength();

                    b.Property<string>("BrowserHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("browser_hash")
                        .IsFixedLength();

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Verifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verifier");

                    b.HasKey("Id")
                        .HasName("tdv2_oauth_attempts_pkey");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("tdv2_oauth_attempts_expiry");

                    b.ToTable("tdv2_oauth_attempts", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.ResponsibleUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id_ur");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cve_ur");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("desc_ur");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("num_empleado");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo_ur");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_ur");

                    b.Property<string>("Manager")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("encargado");

                    b.Property<string>("ParentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id_ur_pertenece");

                    b.Property<bool>("Present")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("presente");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estatus_ur");

                    b.Property<DateTime?>("SynchronizedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sincronizado_en");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.HasKey("Id")
                        .HasName("unidades_responsables_poa_pkey");

                    b.HasIndex("EmployeeNumber")
                        .HasDatabaseName("unidades_responsables_poa_num_empleado_index");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("unidades_responsables_poa_id_ur_pertenece_index");

                    b.ToTable("unidades_responsables_poa", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.SessionTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("id_hash")
                        .IsFixedLength();

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket");

                    b.HasKey("Id")
                        .HasName("tdv2_sessions_pkey");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("tdv2_sessions_expiry");

                    b.ToTable("tdv2_sessions", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.SynchronizationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("terminada_en");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("solicitada_en");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("solicitado_por");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("resultado");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fuentes");

                    b.Property<string>("Stage")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("etapa");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("iniciada_en");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.HasKey("Id")
                        .HasName("sincronizacion_ejecuciones_pkey");

                    b.HasIndex("State")
                        .HasDatabaseName("sincronizacion_ejecuciones_estado_index");

                    b.ToTable("sincronizacion_ejecuciones", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.SynchronizationSettings", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("activa");

                    b.Property<Guid?>("ActiveRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_activa");

                    b.Property<bool>("IncludeIlda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("incluir_ilda");

                    b.Property<int>("IntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("intervalo_minutos");

                    b.Property<DateTime?>("NextAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("proxima_en");

                    b.Property<Guid?>("Owner")
                        .HasColumnType("uuid")
                        .HasColumnName("propietario");

                    b.Property<DateTime?>("ProcessorSeenAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("procesador_visto_en");

                    b.Property<DateTime?>("ReservedUntil")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reserva_hasta");

                    b.Property<string>("Time")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("08:00")
                        .HasColumnName("hora");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("America/Ciudad_Juarez")
                        .HasColumnName("zona_horaria");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("actualizado_por");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("sincronizacion_configuracion_pkey");

                    b.HasIndex("ActiveRunId")
                        .HasDatabaseName("IX_sincronizacion_configuracion_ejecucion_activa");

                    b.ToTable("sincronizacion_configuracion", "public", t =>
                        {
                            t.HasCheckConstraint("sincronizacion_configuracion_id_check", "id = 1");
                        });
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.UnitCollaboration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<bool>("CentralRemovalPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("retiro_central_pendiente");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("num_empleado");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("otorgado_por");

                    b.Property<string>("GrantorUnitId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ur_otorgante");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("tipo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<long>("NexoGrantId")
                        .HasColumnType("bigint")
                        .HasColumnName("nexo_concesion_id");

                    b.Property<long>("NexoRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("nexo_rol_id");

                    b.Property<string>("OriginUnitId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id_ur_origen");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revocada_en");

                    b.Property<string>("ScopeUnitId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id_ur_alcance");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("colaboraciones_ur_pkey");

                    b.HasAlternateKey("NexoGrantId", "ScopeUnitId")
                        .HasName("colaboracion_concesion_alcance_unique");

                    b.ToTable("colaboraciones_ur", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.UnitForm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("contenido");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("porcentaje");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("envio_id");

                    b.Property<string>("SubmissionSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("instantanea_envio");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_en");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("enviado_por");

                    b.Property<string>("SubmittedEffective")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("enviado_como");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id_ur");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("actualizado_por");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.HasKey("Id")
                        .HasName("formatos_ur_pkey");

                    b.HasAlternateKey("UnitId")
                        .HasName("formatos_ur_id_ur_key");

                    b.ToTable("formatos_ur", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<Guid?>("MicrosoftId")
                        .HasColumnType("uuid")
                        .HasColumnName("microsoft_id");

                    b.Property<Guid?>("MicrosoftTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("microsoft_tenant_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("RememberToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("remember_token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasAlternateKey("Email")
                        .HasName("users_email_key");

                    b.HasIndex("MicrosoftTenantId", "MicrosoftId")
                        .IsUnique()
                        .HasDatabaseName("users_microsoft_identity_unique");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.AccessContext", b =>
                {
                    b.HasOne("Tdv2.Domain.Entities.SessionTicket", "Session")
                        .WithOne("Context")
                        .HasForeignKey("Tdv2.Domain.Entities.AccessContext", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tdv2_access_contexts_session_hash_fkey");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.FormBlock", b =>
                {
                    b.HasOne("Tdv2.Domain.Entities.UnitForm", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .HasPrincipalKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.FormMutation", b =>
                {
                    b.HasOne("Tdv2.Domain.Entities.UnitForm", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .HasPrincipalKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.FormPosition", b =>
                {
                    b.HasOne("Tdv2.Domain.Entities.UnitForm", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .HasPrincipalKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.SynchronizationSettings", b =>
                {
                    b.HasOne("Tdv2.Domain.Entities.SynchronizationRun", "ActiveRun")
                        .WithMany()
                        .HasForeignKey("ActiveRunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("sincronizacion_configuracion_ejecucion_activa_fkey");

                    b.Navigation("ActiveRun");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.UnitForm", b =>
                {
                    b.HasOne("Tdv2.Domain.Entities.ResponsibleUnit", "Unit")
                        .WithOne("Form")
                        .HasForeignKey("Tdv2.Domain.Entities.UnitForm", "UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("formatos_ur_id_ur_fkey");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.ResponsibleUnit", b =>
                {
                    b.Navigation("Form");
                });

            modelBuilder.Entity("Tdv2.Domain.Entities.SessionTicket", b =>
                {
                    b.Navigation("Context");
                });
#pragma warning restore 612, 618
        }
    }
}
